### ISSUE TITLE
[Feature request] API

### ISSUE THREAD

**Issue by Niek** [NikolaiT/zardaxt#1]
Would it be possible to add a simple API like p0f to quickly retrieve stats for a given IP address? That would be faster than watching the `fingerprints.json` file for changes.

Another approach is to write the entries to a SQLite file that can be queried by an external service.

**Comment by NikolaiT** [comment]
Yeah that sounds reasonable. I am just afraid that writing a SQLite database is also quite slow, because on large servers, there are a lot of TCP/IP SYN packets coming in.... I need to think of something

**Comment by NikolaiT** [comment]
Added API support in commit 3a009b08d519120b451ff1d98375ac74988923e1.

Api starts automatically when invoking the app.

Example: `curl http://0.0.0.0:8249/classify`

**Comment by Niek** [comment]
Awesome, thanks a lot! 😁🎉
