### ISSUE TITLE
Unable to run tcp_fingerprint.py due to insufficient permissions

### ISSUE THREAD

**Issue by JohnnyRacer** [NikolaiT/zardaxt#13]
Hello, 
I am trying to get this library working but am having trouble with libpcap requiring root permissions. I've seen another issue that was closed with 'just run it as sudo', but this is dangerous as it breaks file permissions with `pip` and defaults to using the Python binary inside `/usr/bin/python` which does not working with using any environment managers like `conda` or `pipenv`. Is there a fix to get around this problem? 

This is the message that pops up when I try to run `tcp_fingerprint.py`
```
[2022-09-19 01:40:41.545098] - INFO - tcp_fingerprint - Loaded 2916 fingerprints from the database

[2022-09-19 01:40:41.545304] - INFO - tcp_fingerprint - listening on interface enp6s0

enp6s0: You don't have permission to capture on that device (socket: Operation not permitted)
```

**Comment by jja67** [comment]
i face the same issue .  if I add sudo to run the python file, then it would still fail as said the module is missing

**Comment by newedgex** [comment]
I'm having the same problem.. Tried also sudo setcap cap_net_admin,cap_net_raw=ep  tcp_fingerprint.py but it didn't work

**Comment by NikolaiT** [comment]
Guys you need to set the correct environment variables.
