### ISSUE TITLE
Cannot install pypacker

### ISSUE THREAD

**Issue by JaviDebrain** [NikolaiT/zardaxt#16]
When running the command `pipenv install pypacker pcapy-ng untangle requests` I'm getting the following error:

× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in pypacker setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.3.*'

**Comment by NikolaiT** [comment]
using `dpkt` now
