### ISSUE TITLE
how to set up the zardaxt server with https support 

### ISSUE THREAD

**Issue by ngloom** [NikolaiT/zardaxt#17]
First thing first , thanks for the great work, really help my work.
Second, It will fail to get the correct client fingerprint when zardaxt is running behind a reverse proxy like nginx,  did anyone know how to set this server with https support if nginx is not avaible ?

**Comment by NikolaiT** [comment]
This my nginx config with certbot (I will also add this to readme.md):

```
server {
  listen 443 ssl;
  server_name tcpip.incolumitas.com;

  location / {
    proxy_pass http://localhost:8249;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Host $host;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_cache_bypass $http_upgrade;
  }
    ssl_certificate /etc/letsencrypt/live/abs.incolumitas.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/abs.incolumitas.com/privkey.pem; # managed by Certbot
}
```

**Comment by ngloom** [comment]
Thanks @NikolaiT 
it really works.   : )

**Comment by NikolaiT** [comment]
> it really works. : )

You phrased that in a way such that my stuff usually not works...Hehe just joking
