### ISSUE TITLE
How did you make up this dataset?

### ISSUE THREAD

**Issue by CidoLiu** [NikolaiT/zardaxt#3]
If I want to extend this dataset, what can I do for this?

**Comment by NikolaiT** [comment]
basically you have to record traffic on your website with some kind of javascript library.

you will need to check whether the `navigator.userAgent` is the same as the http header User-Agent and other means to verify that it's unspoofed and organic traffic. 

Hope that helps. Feel free to ask more questions.

**Comment by CidoLiu** [comment]
Thank you for your reply, so do I need to control many machines with different operating systems? Like Windows, Linux, macOS with a different version. I am not sure whether the virtual machine can truly reflect the parameters in the traffic packet.

**Comment by CidoLiu** [comment]
Or you have a popular website with embedded JavaScript, which is visited by a large number of users and constructs the dataset by collecting traffic on the server.

**Comment by NikolaiT** [comment]
i have a blog where I record sessions on https://bot.incolumitas.com/.

I disregard sessions that don't appear to be human.

**Comment by CidoLiu** [comment]
Thank you very much.
