### ISSUE TITLE
You don't have permission to capture on that device

### ISSUE THREAD

**Issue by workingxx92** [NikolaiT/zardaxt#7]
(zardaxt) bash-3.2$ python tcp_fingerprint.py -i eth0 --classify
WARNING (<module>): Couldn't load netifaces, some utils won't work
Loaded 3203 fingerprints from the database
listening on interface eth0
eth0: You don't have permission to capture on that device ((cannot open BPF device) /dev/bpf0: Permission denied)
(zardaxt) bash-3.2$ 

Os Version: macos Big sur

**Comment by NikolaiT** [comment]
`sudo python tcp_fingerprint.py -i eth0 --classify`

Rule of thumb: If it does not work, always put `sudo` in front of it...just kidding

**Comment by workingxx92** [comment]
@NikolaiT 
I get an error when  put sudo
Macbooks-MacBook-Pro:zardaxt macbookpro$ sudo python tcp_fingerprint.py -i eth0 --classify
Password:
  File "tcp_fingerprint.py", line 320
    print(e, end='\n', flush=True)
                ^
SyntaxError: invalid syntax
Macbooks-MacBook-Pro:zardaxt macbookpro$ sudo python tcp_fingerprint.py -i eth0 --classify
  File "tcp_fingerprint.py", line 320
    print(e, end='\n', flush=True)
                ^
SyntaxError: invalid syntax
